---
services:
  hath:
    container_name: "hath"
    image: "cloverdefa/hath:latest"
    restart: "unless-stopped"
    networks:
      - "hath-networks"
    prots:
      - "12345:12345" # 修改HATH設定PORT
    user: "${ID}" # .env內ID:設定UID及GID
    volumes:
      - "./cache:/hath/cache"
      - "./data:/hath/data"
      - "./download:/hath/download"
      - "./log:/hath/log"
      - "./tmp:/hath/tmp"
    environment:
      PROXY_HOST: "111.222.333.444" # 非必要選項 proxy hostname or IP
      PROXY_TYPE: "socks" # 非必要選項 Proxy 類型 "socks" 或 "http". 空白則使用預設 "socks"
      PROXY_PORT: "1080" # 非必要選項 Proxy Port，空白則預設 SOCKS 為 1080，HTTP 為 8080
      # 編輯同路徑資料夾下的.env檔案來設定ID及KEY
      HATH_CLIENT_ID: "${HATH_CLIENT_ID}"
      HATH_CLIENT_KEY: "${HATH_CLIENT_KEY}"
      UMASK: "000"
      TZ: "Asia/Taipei" # 設定主機所在時區
    env_file: "./.env"

networks:
  hath-networks:
    name: "hath-networks"
