version: "3.9"

services:
  hath:
    container_name: hath
    image: cloverdefa/hath:latest
    restart: unless-stopped
    network_mode: host
    user: ${ID} # 使用 .env 內設定的 UID:GID
    volumes:
      - ./cache:/hath/cache
      - ./data:/hath/data
      - ./download:/hath/download
      - ./log:/hath/log
      - ./tmp:/hath/tmp
    environment:
      HATH_CLIENT_ID: ${HATH_CLIENT_ID} # 使用 .env 內設定的 H@H Client ID
      HATH_CLIENT_KEY: ${HATH_CLIENT_KEY} # 使用 .env 內設定的 H@H Client KEY
      UMASK: '000'
      TZ: 'Asia/Taipei' # 設定主機所在時區
