version: "3.9"

services:
  hath:
    container_name: hath
    image: cloverdefa/hath:latest
    restart: unless-stopped
    network_mode: host
    user: '${UID}:${GID}'
    volumes:
      - ./cache:/hath/cache
      - ./data:/hath/data
      - ./download:/hath/download
      - ./log:/hath/log
      - ./tmp:/hath/tmp
    environment:
      # 編輯同路徑資料夾下的.env檔案來設定ID及KEY   
      HATH_CLIENT_ID: $(HATH_CLIENT_ID) # 載入.env H@H Client ID   
      HATH_CLIENT_KEY: $(HATH_CLIENT_KEY) # 載入.env H@H Client KEY   
      UMASK: '000'
      TZ: 'Asia/Taipei' # 設定主機所在時區
