name: Telegram Notification Push

on:
  push

jobs:

  bulid:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.BOT_ID }}
        token: ${{ secrets.BOT_TOKEN }}
        # github.actor: 觸發 event 的使用者名稱
        # github.sha: commit 的 hash 值
        # github.event.commits[0].message: commit message
        # github.repository: repository 的名稱
        message: |
          ${{ github.actor }} 提交內容: 
          ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}
