name: Create pull request
on:
  push:
    branches:
      - feature
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main