name: Telegram Notification Push

on:
  push

jobs:

  bulid:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} 提交內容: 
          ${{ github.event.commits[0].message }}
          存儲庫: ${{ github.repository }}
